"""The poster designs a workspace starts with.

Seeded per tenant at provisioning so an agent has something to send on day one
rather than a blank canvas. They are ordinary templates once created — editable,
deletable, and not overwritten by an upgrade.
"""

#: Merge fields available in poster text, and what a preview shows for each.
MERGE_FIELDS = {
    "customer_name": "Anand Krishnan",
    "first_name": "Anand",
    "policy_number": "MOT/2026/00145",
    "insurer": "HDFC ERGO",
    "expiry_date": "02 Oct 2026",
    "days_to_expiry": "14",
    "premium": "₹16,756",
    "vehicle_no": "TN09BX4471",
    "product_line": "Motor",
    "agent_name": "Insurance Admin",
    "agent_mobile": "+91 98430 12345",
    "agency_name": "Insurance Agency",
}

PRESETS = [
    {
        "name": "Birthday wishes",
        "category": "birthday",
        "size": "square",
        "order": 1,
        "background": {"color": "#4F46E5"},
        "layers": [
            {"type": "rect", "x": 60, "y": 60, "w": 960, "h": 960, "fill": "#FFFFFF", "radius": 48},
            {"type": "text", "x": 120, "y": 200, "w": 840, "text": "Happy Birthday",
             "size": 92, "bold": True, "color": "#4F46E5", "align": "center"},
            {"type": "text", "x": 120, "y": 340, "w": 840, "text": "{customer_name}",
             "size": 64, "bold": True, "color": "#1E293B", "align": "center", "max_lines": 2},
            {"type": "text", "x": 140, "y": 500, "w": 800,
             "text": "Wishing you a wonderful year ahead, filled with good health and happiness.",
             "size": 38, "color": "#475569", "align": "center", "max_lines": 3},
            {"type": "rect", "x": 420, "y": 700, "w": 240, "h": 4, "fill": "#E2E8F0"},
            {"type": "text", "x": 120, "y": 760, "w": 840, "text": "{agent_name}",
             "size": 36, "bold": True, "color": "#1E293B", "align": "center"},
            {"type": "text", "x": 120, "y": 812, "w": 840, "text": "{agency_name} · {agent_mobile}",
             "size": 28, "color": "#64748B", "align": "center"},
        ],
    },
    {
        "name": "Renewal reminder",
        "category": "renewal",
        "size": "square",
        "order": 2,
        "background": {"color": "#0F172A"},
        "layers": [
            {"type": "rect", "x": 0, "y": 0, "w": 1080, "h": 320, "fill": "#F59E0B"},
            {"type": "text", "x": 80, "y": 110, "w": 920, "text": "POLICY RENEWAL DUE",
             "size": 68, "bold": True, "color": "#0F172A", "align": "center"},
            {"type": "text", "x": 80, "y": 210, "w": 920, "text": "in {days_to_expiry} days",
             "size": 40, "color": "#78350F", "align": "center"},
            {"type": "text", "x": 80, "y": 420, "w": 920, "text": "{customer_name}",
             "size": 56, "bold": True, "color": "#FFFFFF", "align": "center", "max_lines": 2},
            {"type": "text", "x": 80, "y": 520, "w": 920,
             "text": "Your {product_line} policy {policy_number} with {insurer} expires on {expiry_date}.",
             "size": 34, "color": "#CBD5E1", "align": "center", "max_lines": 4},
            # Both halves of the call-to-action depend on the number; without one on
            # file the whole button disappears rather than leaving an empty pill.
            {"type": "rect", "x": 240, "y": 720, "w": 600, "h": 96, "fill": "#F59E0B", "radius": 48,
             "requires": "agent_mobile"},
            {"type": "text", "x": 240, "y": 748, "w": 600, "text": "Call {agent_mobile}",
             "size": 38, "bold": True, "color": "#0F172A", "align": "center",
             "requires": "agent_mobile"},
            {"type": "text", "x": 80, "y": 900, "w": 920, "text": "{agent_name} · {agency_name}",
             "size": 28, "color": "#94A3B8", "align": "center"},
        ],
    },
    {
        "name": "Policy issued",
        "category": "issued",
        "size": "square",
        "order": 3,
        "background": {"color": "#065F46"},
        "layers": [
            {"type": "text", "x": 80, "y": 220, "w": 920, "text": "You're covered",
             "size": 86, "bold": True, "color": "#FFFFFF", "align": "center"},
            {"type": "text", "x": 80, "y": 360, "w": 920, "text": "{customer_name}",
             "size": 52, "color": "#A7F3D0", "align": "center", "max_lines": 2},
            {"type": "rect", "x": 120, "y": 480, "w": 840, "h": 260, "fill": "#FFFFFF", "radius": 32},
            {"type": "text", "x": 160, "y": 530, "w": 760, "text": "{policy_number}",
             "size": 44, "bold": True, "color": "#065F46", "align": "center"},
            {"type": "text", "x": 160, "y": 606, "w": 760, "text": "{insurer} · {product_line}",
             "size": 32, "color": "#475569", "align": "center"},
            {"type": "text", "x": 160, "y": 660, "w": 760, "text": "Valid until {expiry_date}",
             "size": 30, "color": "#64748B", "align": "center"},
            {"type": "text", "x": 80, "y": 860, "w": 920, "text": "{agent_name} · {agent_mobile}",
             "size": 30, "color": "#A7F3D0", "align": "center"},
        ],
    },
    {
        "name": "Festival greeting",
        "category": "festival",
        "size": "square",
        "order": 4,
        "background": {"color": "#7C2D12"},
        "layers": [
            {"type": "rect", "x": 80, "y": 80, "w": 920, "h": 920, "fill": "#FEF3C7", "radius": 24},
            {"type": "text", "x": 140, "y": 300, "w": 800, "text": "Season's Greetings",
             "size": 74, "bold": True, "color": "#7C2D12", "align": "center", "max_lines": 2},
            {"type": "text", "x": 140, "y": 470, "w": 800, "text": "{customer_name}",
             "size": 46, "color": "#92400E", "align": "center", "max_lines": 2},
            {"type": "text", "x": 160, "y": 580, "w": 760,
             "text": "May this festive season bring you prosperity, health and peace of mind.",
             "size": 34, "color": "#78350F", "align": "center", "max_lines": 3},
            {"type": "text", "x": 140, "y": 800, "w": 800, "text": "{agency_name}",
             "size": 34, "bold": True, "color": "#7C2D12", "align": "center"},
            {"type": "text", "x": 140, "y": 850, "w": 800, "text": "{agent_name} · {agent_mobile}",
             "size": 28, "color": "#92400E", "align": "center"},
        ],
    },
    {
        "name": "Renewal reminder (story)",
        "category": "renewal",
        "size": "story",
        "order": 5,
        "background": {"color": "#1E293B"},
        "layers": [
            {"type": "rect", "x": 0, "y": 0, "w": 1080, "h": 420, "fill": "#4F46E5"},
            {"type": "text", "x": 80, "y": 180, "w": 920, "text": "RENEWAL DUE",
             "size": 78, "bold": True, "color": "#FFFFFF", "align": "center"},
            {"type": "text", "x": 80, "y": 290, "w": 920, "text": "in {days_to_expiry} days",
             "size": 42, "color": "#C7D2FE", "align": "center"},
            {"type": "text", "x": 80, "y": 700, "w": 920, "text": "{customer_name}",
             "size": 64, "bold": True, "color": "#FFFFFF", "align": "center", "max_lines": 2},
            {"type": "text", "x": 80, "y": 860, "w": 920, "text": "{policy_number}",
             "size": 44, "color": "#94A3B8", "align": "center"},
            {"type": "text", "x": 80, "y": 940, "w": 920, "text": "{insurer} · expires {expiry_date}",
             "size": 34, "color": "#94A3B8", "align": "center", "max_lines": 2},
            {"type": "rect", "x": 190, "y": 1180, "w": 700, "h": 110, "fill": "#4F46E5", "radius": 55,
             "requires": "agent_mobile"},
            {"type": "text", "x": 190, "y": 1212, "w": 700, "text": "Renew now",
             "size": 44, "bold": True, "color": "#FFFFFF", "align": "center",
             "requires": "agent_mobile"},
            {"type": "text", "x": 80, "y": 1700, "w": 920, "text": "{agent_name}",
             "size": 40, "bold": True, "color": "#FFFFFF", "align": "center"},
            {"type": "text", "x": 80, "y": 1760, "w": 920, "text": "{agency_name} · {agent_mobile}",
             "size": 30, "color": "#94A3B8", "align": "center"},
        ],
    },
]
