"""Multi-tenancy: tenants table, tenant_id everywhere, per-tenant unique constraints.

Written by hand rather than autogenerated because the interesting part is the data
migration: every existing row belongs to one Default tenant, and that tenant has to
exist before `tenant_id` can be made meaningful.

Order matters:
  1. create `tenants` and `platform_audit_logs`
  2. add nullable `tenant_id` to every business table
  3. create the Default tenant and backfill every row to it
  4. swap global unique constraints for per-tenant ones
  5. add the platform-admin columns to `users`

SQLite cannot ALTER constraints, so step 4 runs through Alembic's batch mode, which
rebuilds each table. On Postgres the same code emits plain ALTERs.

Revision ID: 0002_multitenant
Revises: 0001_baseline
"""

import uuid
from datetime import datetime

import sqlalchemy as sa
from alembic import op

revision = "0002_multitenant"
down_revision = "0001_baseline"
branch_labels = None
depends_on = None


# Every table that gains a tenant_id.
TENANT_TABLES = [
    "roles", "users", "companies", "contacts", "lead_sources", "leads",
    "deal_stages", "deals", "activities", "audit_logs", "tasks", "comments",
    "meetings", "calendar_events", "products", "quotations", "quotation_items",
    "invoices", "invoice_items", "projects", "project_tasks", "documents",
    "tickets", "notifications", "settings", "email_templates", "tags",
]

# (table, column, old global index/constraint name, new per-tenant constraint name)
UNIQUE_SWAPS = [
    ("roles", "name", "uq_roles_tenant_name"),
    ("lead_sources", "name", "uq_lead_sources_tenant_name"),
    ("deal_stages", "name", "uq_deal_stages_tenant_name"),
    ("products", "sku", "uq_products_tenant_sku"),
    ("quotations", "number", "uq_quotations_tenant_number"),
    ("invoices", "number", "uq_invoices_tenant_number"),
    ("tickets", "number", "uq_tickets_tenant_number"),
    ("settings", "key", "uq_settings_tenant_key"),
    ("email_templates", "name", "uq_email_templates_tenant_name"),
    ("tags", "name", "uq_tags_tenant_name"),
]

DEFAULT_TENANT_SLUG = "default"


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    # 1. platform tables -------------------------------------------------------
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("template_key", sa.String(length=50), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("default_country_code", sa.String(length=5), nullable=False),
        sa.Column("dek_encrypted", sa.Text(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("owner_user_id", sa.String(length=32), nullable=True),
        sa.Column("suspended_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tenants_created_at", "tenants", ["created_at"])
    op.create_index("ix_tenants_name", "tenants", ["name"])
    op.create_index("ix_tenants_slug", "tenants", ["slug"], unique=True)
    op.create_index("ix_tenants_status", "tenants", ["status"])

    op.create_table(
        "platform_audit_logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_user_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("tenant_id_ref", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_platform_audit_logs_created_at", "platform_audit_logs", ["created_at"])
    op.create_index("ix_platform_audit_logs_action", "platform_audit_logs", ["action"])
    op.create_index("ix_platform_audit_logs_tenant_id_ref", "platform_audit_logs", ["tenant_id_ref"])

    # 2. tenant_id on every business table -------------------------------------
    for table in TENANT_TABLES:
        if table not in existing:
            continue
        op.add_column(table, sa.Column("tenant_id", sa.String(length=32), nullable=True))
        op.create_index(f"ix_{table}_tenant_id", table, ["tenant_id"])

    # 3. the Default tenant, and every existing row assigned to it -------------
    now = datetime.utcnow()
    default_tenant_id = uuid.uuid4().hex
    op.execute(
        sa.text(
            "INSERT INTO tenants (id, created_at, updated_at, name, slug, type, status, "
            "template_key, plan, timezone, currency, locale, default_country_code, "
            "settings, owner_user_id, suspended_at, deleted_at) "
            "VALUES (:id, :now, :now, :name, :slug, 'company', 'active', 'general_crm', "
            "'standard', 'Asia/Kolkata', 'INR', 'en-IN', '+91', '{}', NULL, NULL, NULL)"
        ).bindparams(id=default_tenant_id, now=now, name="Default Workspace", slug=DEFAULT_TENANT_SLUG)
    )

    for table in TENANT_TABLES:
        if table not in existing:
            continue
        op.execute(
            sa.text(f"UPDATE {table} SET tenant_id = :tid WHERE tenant_id IS NULL").bindparams(
                tid=default_tenant_id
            )
        )

    # 4. per-tenant unique constraints ----------------------------------------
    # A global UNIQUE on e.g. settings.key would stop two tenants ever holding the
    # same key, so each one becomes UNIQUE(tenant_id, key).
    #
    # SQLite renders `unique=True` as an *unnamed* table constraint, and Alembic's
    # batch mode cannot drop a constraint it cannot name. The workaround is to
    # reflect the table, discard the offending constraint from the reflected
    # definition, and hand that to batch_alter_table as `copy_from` — the table is
    # then rebuilt without it.
    for table, column, new_name in UNIQUE_SWAPS:
        if table not in existing:
            continue

        # Named unique *indexes* can be dropped directly; do that before reflecting.
        for index in sa.inspect(bind).get_indexes(table):
            if index.get("unique") and index.get("column_names") == [column] and index.get("name"):
                op.drop_index(index["name"], table_name=table)

        reflected = sa.Table(table, sa.MetaData(), autoload_with=bind)
        for constraint in list(reflected.constraints):
            if isinstance(constraint, sa.UniqueConstraint) and [
                c.name for c in constraint.columns
            ] == [column]:
                reflected.constraints.discard(constraint)

        with op.batch_alter_table(table, copy_from=reflected) as batch:
            batch.create_unique_constraint(new_name, ["tenant_id", column])

        # Still looked up on its own, so keep a plain (non-unique) index.
        op.create_index(f"ix_{table}_{column}", table, [column])

    # 5. platform admin columns; role becomes optional for platform users ------
    op.add_column("users", sa.Column("is_platform_admin", sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_platform_admin = 0 WHERE is_platform_admin IS NULL")
    with op.batch_alter_table("users") as batch:
        batch.alter_column("is_platform_admin", existing_type=sa.Boolean(), nullable=False)
        batch.alter_column("role_id", existing_type=sa.String(length=32), nullable=True)
    op.create_index("ix_users_is_platform_admin", "users", ["is_platform_admin"])


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    op.drop_index("ix_users_is_platform_admin", table_name="users")
    op.drop_column("users", "is_platform_admin")

    for table, column, new_name in UNIQUE_SWAPS:
        if table not in existing:
            continue
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(new_name, type_="unique")
            batch.create_index(f"ix_{table}_{column}_unique", [column], unique=True)

    for table in TENANT_TABLES:
        if table not in existing:
            continue
        op.drop_index(f"ix_{table}_tenant_id", table_name=table)
        op.drop_column(table, "tenant_id")

    op.drop_table("platform_audit_logs")
    op.drop_table("tenants")
