"""The insurance customer record: personal fields, encrypted identity, nominees, notes.

Hand-written rather than autogenerated: against SQLite, autogenerate reports the
foreign keys and NOT NULLs that earlier batch rebuilds left implicit, and would
rebuild every table to "fix" them.

All new contact columns are nullable. A general CRM tenant simply leaves them empty,
and its template does not surface them, so nothing changes for an existing workspace.

PAN and Aadhaar are stored as ciphertext (`*_encrypted`) with a keyed-hash companion
(`*_index`) for exact-match lookup — an encrypted column cannot be searched, because
two encryptions of the same value differ. `aadhaar_last4` is stored separately
because it is what masking shows and, for most intermediaries, all they should keep.

Revision ID: 0005_customer_pii
Revises: 0004_custom_fields
"""

import sqlalchemy as sa
from alembic import op

revision = "0005_customer_pii"
down_revision = "0004_custom_fields"
branch_labels = None
depends_on = None

CONTACT_COLUMNS = [
    ("date_of_birth", sa.Date()),
    ("birthday_key", sa.String(length=4)),
    ("gender", sa.String(length=20)),
    ("marital_status", sa.String(length=20)),
    ("occupation", sa.String(length=150)),
    ("annual_income", sa.Integer()),
    ("mobile", sa.String(length=20)),
    ("alt_mobile", sa.String(length=20)),
    ("alt_email", sa.String(length=255)),
    ("address_line", sa.Text()),
    ("pincode", sa.String(length=6)),
    ("city", sa.String(length=100)),
    ("state", sa.String(length=100)),
    ("pan_encrypted", sa.Text()),
    ("pan_index", sa.String(length=64)),
    ("aadhaar_encrypted", sa.Text()),
    ("aadhaar_index", sa.String(length=64)),
    ("aadhaar_last4", sa.String(length=4)),
    ("stage", sa.String(length=50)),
    ("referred_by_type", sa.String(length=20)),
    ("referred_by_contact_id", sa.String(length=32)),
    ("referred_by_name", sa.String(length=200)),
    ("referred_on", sa.Date()),
    ("products_of_interest", sa.JSON()),
]

# Indexed because each one is queried on its own: birthdays by day, customers by
# mobile or pincode, identity by blind index, lists by stage.
CONTACT_INDEXES = [
    "date_of_birth", "birthday_key", "mobile", "pincode",
    "pan_index", "aadhaar_index", "stage",
]


def upgrade() -> None:
    for name, type_ in CONTACT_COLUMNS:
        op.add_column("contacts", sa.Column(name, type_, nullable=True))
    op.execute("UPDATE contacts SET products_of_interest = '[]' WHERE products_of_interest IS NULL")
    for name in CONTACT_INDEXES:
        op.create_index(f"ix_contacts_{name}", "contacts", [name])

    op.create_table(
        "nominees",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=True),
        sa.Column("contact_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("share_percent", sa.Integer(), nullable=False),
        sa.Column("appointee_name", sa.String(length=200), nullable=True),
        sa.Column("appointee_relation", sa.String(length=50), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_nominees_created_at", "nominees", ["created_at"])
    op.create_index("ix_nominees_tenant_id", "nominees", ["tenant_id"])
    op.create_index("ix_nominees_contact_id", "nominees", ["contact_id"])

    op.create_table(
        "customer_notes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=True),
        sa.Column("contact_id", sa.String(length=32), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author_id", sa.String(length=32), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_customer_notes_created_at", "customer_notes", ["created_at"])
    op.create_index("ix_customer_notes_tenant_id", "customer_notes", ["tenant_id"])
    op.create_index("ix_customer_notes_contact_id", "customer_notes", ["contact_id"])


def downgrade() -> None:
    op.drop_table("customer_notes")
    op.drop_table("nominees")
    for name in CONTACT_INDEXES:
        op.drop_index(f"ix_contacts_{name}", table_name="contacts")
    for name, _ in CONTACT_COLUMNS:
        op.drop_column("contacts", name)
